### ISSUE TITLE
Proses invoice GoThru Media, Inc,

### ISSUE THREAD

**Issue by aliyawanaris** [anurdin01/Test-Repo-123-B#13]

**Comment by anurdin01** [comment]
selain PDF sertakan juga link docs nya, untuk berjaga-jaga jika perlu ada update dari saya

**Comment by rizalhusni195** [comment]
Data Invoce ke GoThru Media, Inc. Periode November 2024
- [x] File invoice pdf [Link](https://github.com/user-attachments/files/17810390/INVOICE.November.2024.pdf)
- [x] File invoice doc [Link](https://docs.google.com/document/d/1oYy5FUgRQW09v3JdtphTVWS8FlCyAfvCa0_eQc0YZp4/edit?usp=sharing)
- [x] File Detail Omzet [Link](https://docs.google.com/spreadsheets/d/1e0ZwNaYo8IQkmKXfx9MiwCS8HhjxlcNjpun5MCmuJHM/edit?usp=sharing)
