### ISSUE TITLE
Validasi penggajian November 2024

### ISSUE THREAD

**Issue by aliyawanaris** [anurdin01/Test-Repo-123-B#32]
- Apakah dolar yang di invoice kmarin total Rp110,206,225 + Rp88,284,625 (tidak jauh dari angka ini karena dolar naik turun)?
- Check/validasi proses penggajian khawatir ada double pembayaran
- Validasi pembayaran, khawatir ada yang belum/tidak sesuai

**Comment by rizalhusni195** [comment]
- [x] Validasi[Link](https://docs.google.com/spreadsheets/d/10aLzoHNu5ewIXwSL0nJxs26mhMCfYxZKIExVAlcbCgY/edit?gid=543259938#gid=543259938)
