### ISSUE TITLE
SQA Testing Report - Street Editor

### ISSUE THREAD

**Issue by aliyawanaris** [anurdin01/Test-Repo-123-B#37]
Menyusun, membuat laporan SQA testing report project Street Editor
- SQA Testing Report - Unit Testing
- SQA Testing Report - Sanity Testing

**Comment by rizalhusni195** [comment]
- [x] Unity Testing [Link](https://github.com/GoThruMedia/street-editor/issues/249#issue-2678167610)
- [x] Sanity Testing [link](https://github.com/GoThruMedia/street-editor/issues/250#issuecomment-2500174754)
