### ISSUE TITLE
Testing Rangga (Selasa, 19/11/2024)

### ISSUE THREAD

**Issue by aliyawanaris** [anurdin01/Test-Repo-123-B#9]
Test experience app on mobile device

BUILD STREET EDITOR 2.1.7 
https://expo.dev/artifacts/eas/vtfT4kK7weMJRD5SG6fpvA.apk

**Comment by anurdin01** [comment]
pastikan report nya d stok ke eko

**Comment by aliyawanaris** [comment]
When add a photo, a tour map out of the app.

https://github.com/user-attachments/assets/964b6d15-ba32-4564-aff0-d5a31f8eb550

**Comment by aliyawanaris** [comment]
Connect panorama missing component preview

https://github.com/user-attachments/assets/6c3b4c24-9f8d-4101-8ccb-5a406bcba52a
